import numpy as np
from typing import Any, Type, Optional, Tuple, Union, List, Dict, Iterator
from itertools import combinations
from mosek.fusion import Model, Domain, ObjectiveSense, OptimizeError
import mosek.fusion.pythonic
from autolyap.utils.helper_functions import create_symmetric_matrix_expression, create_symmetric_matrix
from autolyap.solver_options import (
    SolverOptions,
    normalize_solver_options,
    get_cvxpy_solve_kwargs,
    get_cvxpy_accepted_statuses,
)
from autolyap.utils.validation import (
    ensure_finite_array,
    ensure_integral,
)
from autolyap.problemclass import InclusionProblem
from autolyap.algorithms import Algorithm

Pair = Union[Tuple[int, int], Tuple[str, str]]
PairTuple = Tuple[Pair, ...]
OperatorInterpolationData = Tuple[np.ndarray, str]
FunctionInterpolationData = Tuple[np.ndarray, np.ndarray, bool, str]
InterpolationData = Union[OperatorInterpolationData, FunctionInterpolationData]

class IterationDependent:
    r"""
    Iteration-dependent Lyapunov analysis utilities.

    Class-level reference
    =====================

    This class-level docstring centralizes notation shared across methods.
    Method-level docstrings focus on API details: inputs, outputs, and validation.

    **Problem and algorithm context**

    Notation follows :class:`~autolyap.problemclass.InclusionProblem` and
    :class:`~autolyap.algorithms.Algorithm`.
    The sets :math:`\IndexFunc`, :math:`\IndexOp` and counts
    :math:`\NumEval`, :math:`\NumEvalFunc`, :math:`\NumFunc` are inherited from those classes.
    We consider sequences

    .. math::
        (\bx^{k},\bu^{k},\by^{k},\bFcn^{k})_{k\in\naturals}

    generated by the state-space representation, together with a solution triplet
    :math:`(y^{\star},\hat{\bu}^{\star},\bFcn^{\star})`.

    **Star variables**

    A solution triplet means there exists a vector

    .. math::
        \bu^{\star} = (u_1^{\star},\ldots,u_m^{\star}),

    such that

    .. math::
        \forall i \in \IndexFunc, \quad u_i^{\star}\in\partial f_i(y^{\star}), \qquad
        \forall i \in \IndexOp, \quad u_i^{\star}\in G_i(y^{\star}), \qquad
        \sum_{i=1}^{m} u_i^{\star}=0.

    Hence, each :math:`u_i^{\star}` is the component output at :math:`y^{\star}`.

    The reduced vector :math:`\hat{\bu}^{\star}` collects the first :math:`m-1` components of
    :math:`\bu^{\star}`:

    .. math::
        \hat{\bu}^{\star} = (u_1^{\star},\ldots,u_{m-1}^{\star}), \qquad
        u_m^{\star} = -\sum_{i=1}^{m-1} u_i^{\star}.

    The function-value vector is

    .. math::
        \bFcn^{\star}=(f_i(y^{\star}))_{i\in\IndexFunc}.

    **Lyapunov ansatz**

    Fix a horizon :math:`K \in \naturals`.
    For each :math:`k \in \llbracket 0, K \rrbracket`, define

    .. math::
        \boldsymbol{z}_{\mathcal{V}}^{k}
        =
        \begin{bmatrix}
        \bx^{k} \\ \bu^{k} \\ \hat{\bu}^{\star} \\ y^{\star}
        \end{bmatrix}, \qquad
        \boldsymbol{f}_{\mathcal{V}}^{k}
        =
        \begin{bmatrix}
        \bFcn^{k} \\ \bFcn^{\star}
        \end{bmatrix},

    .. math::
        \mathcal{V}(k)
        =
        \inner{
        \boldsymbol{z}_{\mathcal{V}}^{k}
        }{
        (Q_k \kron \Id)\boldsymbol{z}_{\mathcal{V}}^{k}
        }
        + q_{k}^{\top}\boldsymbol{f}_{\mathcal{V}}^{k}.

    **Dimensions**

    .. math::
        Q_k \in \sym^{n + \NumEval + m}, \qquad
        q_k \in \mathbb{R}^{\NumEvalFunc + \NumFunc}.

    Here :math:`n` is the state dimension (as in :class:`~autolyap.algorithms.Algorithm`).
    The vector :math:`\hat{\bu}^{\star}` is void when :math:`m = 1`.
    When :math:`\NumFunc = 0`, the vectors :math:`q_k` are omitted.

    **Chained Lyapunov inequalities**

    We set the endpoint parameters :math:`(Q_0,q_0)` and :math:`(Q_K,q_K)` and
    search for intermediate :math:`(Q_k,q_k)` for
    :math:`k \in \llbracket 1, K-1 \rrbracket`, together with a scalar :math:`c \ge 0`, such that

    .. math::
        \mathcal{V}(K) \le \mathcal{V}(K-1) \le \cdots \le \mathcal{V}(1) \le c\,\mathcal{V}(0).

    **Role of K**

    - :math:`K` is the iteration budget and final index in the chained inequalities.
    - The chain links the Lyapunov values from :math:`k=0` to :math:`k=K`.

    **Convergence conclusions**

    When the chained inequalities are feasible, there exists :math:`c \ge 0` such that

    .. math::
        \mathcal{V}(K) \le c\,\mathcal{V}(0).

    """
    @staticmethod
    def _import_cvxpy():
        r"""Import cvxpy lazily so MOSEK-only workflows stay lightweight."""
        try:
            import cvxpy as cp
        except ImportError as exc:
            raise ImportError(
                "CVXPY backend requested, but cvxpy is not installed. "
                "Install it with `pip install cvxpy`."
            ) from exc
        return cp

    @staticmethod
    def _apply_mosek_solver_params(mod: Model, solver_options: SolverOptions) -> None:
        r"""Apply user-provided MOSEK Fusion parameters to a model."""
        params = solver_options.mosek_params or {}
        for name, value in params.items():
            mod.setSolverParam(name, value)

    @staticmethod
    def _extract_scalar_variable_value(var: object) -> float:
        r"""Extract a scalar value from either a Fusion variable or a CVXPY variable."""
        if hasattr(var, "level"):
            value_arr = np.asarray(var.level(), dtype=float).reshape(-1)
        elif hasattr(var, "value"):
            value_arr = np.asarray(var.value, dtype=float).reshape(-1)
        else:
            raise ValueError("Unsupported scalar variable handle type.")
        return float(value_arr[0]) if value_arr.size > 0 else 0.0

    @staticmethod
    def _pairs_from_readable(pairs_readable: List[Dict[str, Union[int, str]]]) -> PairTuple:
        r"""Convert readable pair dictionaries back into internal tuple form."""
        pairs: List[Pair] = []
        for pair in pairs_readable:
            j_val = pair["j"]
            k_val = pair["k"]
            if j_val == "star" or k_val == "star":
                pairs.append(("star", "star"))
            else:
                pairs.append((int(j_val), int(k_val)))
        return tuple(pairs)

    @staticmethod
    def _min_symmetric_eigenvalue(matrix: np.ndarray) -> float:
        r"""Return the smallest eigenvalue of a symmetrized matrix."""
        symmetric_matrix = 0.5 * (matrix + matrix.T)
        try:
            eigvals = np.linalg.eigvalsh(symmetric_matrix)
            return float(np.min(eigvals))
        except np.linalg.LinAlgError:
            eigvals = np.linalg.eigvals(symmetric_matrix)
            return float(np.min(np.real(eigvals)))

    @staticmethod
    def _compute_iteration_dependent_diagnostics(
            prob: Type[InclusionProblem],
            algo: Type[Algorithm],
            K: int,
            c_value: float,
            certificate: Dict[str, object],
    ) -> Dict[str, object]:
        r"""Compute post-solve diagnostics for nonnegativity, PSD, and equality constraints."""
        Q_sequence = [np.asarray(Q_k, dtype=float) for Q_k in certificate["Q_sequence"]]
        q_sequence_raw = certificate["q_sequence"]
        q_sequence = None
        if q_sequence_raw is not None:
            q_sequence = [np.asarray(q_k, dtype=float).reshape(-1) for q_k in q_sequence_raw]
        multipliers = certificate["multipliers"]

        nonnegative_records: List[Tuple[str, float]] = [("c", float(c_value))]
        for multiplier_name in ("operator_lambda", "function_lambda"):
            for record in multipliers[multiplier_name]:
                label = (
                    f"{multiplier_name}(iteration={record['iteration']},"
                    f" component={record['component']},"
                    f" interpolation_index={record['interpolation_index']})"
                )
                nonnegative_records.append((label, float(record["value"])))

        negative_nonnegative = [(label, value) for label, value in nonnegative_records if value < 0.0]
        largest_nonnegative_violation = max((-value for _, value in negative_nonnegative), default=0.0)
        worst_nonnegative = min(nonnegative_records, key=lambda item: item[1], default=None)

        Ws: Dict[int, np.ndarray] = {}
        Theta0_0, Theta1_0 = IterationDependent._compute_Thetas(algo, 0)
        Ws[0] = Theta1_0.T @ Q_sequence[1] @ Theta1_0 - c_value * (Theta0_0.T @ Q_sequence[0] @ Theta0_0)
        for k in range(1, K):
            Theta0_k, Theta1_k = IterationDependent._compute_Thetas(algo, k)
            Ws[k] = Theta1_k.T @ Q_sequence[k + 1] @ Theta1_k - Theta0_k.T @ Q_sequence[k] @ Theta0_k

        psd_constraint_sums: Dict[int, np.ndarray] = {k: -np.asarray(Ws[k], dtype=float) for k in range(0, K)}

        all_psd_multiplier_records = (
            multipliers["operator_lambda"]
            + multipliers["function_lambda"]
            + multipliers["function_nu"]
        )
        component_data = {i: prob.get_component_data(i) for i in range(1, algo.m + 1)}

        for record in all_psd_multiplier_records:
            k = int(record["iteration"])
            if k not in psd_constraint_sums:
                continue

            i = int(record["component"])
            interpolation_index = int(record["interpolation_index"])
            value = float(record["value"])
            interpolation_data = component_data[i][interpolation_index]
            M = np.asarray(interpolation_data[0], dtype=float)
            if not np.any(M):
                continue

            pairs = IterationDependent._pairs_from_readable(record["pairs"])
            E_matrix = algo.compute_E(i, list(pairs), k, k + 1, validate=False)
            W_matrix = E_matrix.T @ M @ E_matrix
            psd_constraint_sums[k] = psd_constraint_sums[k] + value * W_matrix

        psd_per_constraint: List[Dict[str, object]] = []
        largest_psd_violation = 0.0
        worst_psd_entry: Optional[Dict[str, object]] = None

        for k in range(0, K):
            min_eigenvalue = IterationDependent._min_symmetric_eigenvalue(psd_constraint_sums[k])
            violation = max(0.0, -min_eigenvalue)
            entry = {
                "label": f"iteration={k}",
                "iteration": k,
                "min_eigenvalue": min_eigenvalue,
                "violation": violation,
            }
            psd_per_constraint.append(entry)
            if worst_psd_entry is None or min_eigenvalue < float(worst_psd_entry["min_eigenvalue"]):
                worst_psd_entry = entry
            if violation > largest_psd_violation:
                largest_psd_violation = violation

        equality_per_constraint: List[Dict[str, object]] = []
        violating_equality_entries = 0
        total_equality_entries = 0
        largest_equality_violation = 0.0
        worst_equality_entry: Optional[Dict[str, object]] = None
        equality_tolerance = 1e-9

        if algo.m_func > 0:
            if q_sequence is None:
                raise ValueError("Certificate is missing q_sequence while functional components are active.")
            m_bar_func = algo.m_bar_func
            m_func = algo.m_func
            theta0, theta1 = IterationDependent._compute_thetas(algo)

            ws: Dict[int, np.ndarray] = {}
            ws[0] = theta1.T @ q_sequence[1] - c_value * (theta0.T @ q_sequence[0])
            for k in range(1, K):
                ws[k] = theta1.T @ q_sequence[k + 1] - theta0.T @ q_sequence[k]

            eq_constraint_sums: Dict[int, np.ndarray] = {
                k: -np.asarray(ws[k], dtype=float).reshape(-1) for k in range(0, K)
            }

            eq_multiplier_records = multipliers["function_lambda"] + multipliers["function_nu"]
            lifted_F_basis_cache: Dict[Tuple[int, int, PairTuple], np.ndarray] = {}

            def _get_lifted_F_basis(k_idx: int, i: int, pairs: PairTuple) -> np.ndarray:
                cache_key = (k_idx, i, pairs)
                F_basis = lifted_F_basis_cache.get(cache_key)
                if F_basis is None:
                    Fs_dict = algo.get_Fs(k_idx, k_idx + 1)
                    total_dim = 2 * m_bar_func + m_func
                    F_basis = np.empty((total_dim, len(pairs)))
                    for col_idx, (j, k_pair) in enumerate(pairs):
                        key = (i, "star", "star") if (j == "star" and k_pair == "star") else (i, j, k_pair)
                        F_basis[:, col_idx] = Fs_dict[key].reshape(-1)
                    lifted_F_basis_cache[cache_key] = F_basis
                return F_basis

            component_data = {i: prob.get_component_data(i) for i in range(1, algo.m + 1)}
            for record in eq_multiplier_records:
                k = int(record["iteration"])
                if k not in eq_constraint_sums:
                    continue

                i = int(record["component"])
                interpolation_index = int(record["interpolation_index"])
                value = float(record["value"])
                interpolation_data = component_data[i][interpolation_index]
                a_vec = np.asarray(interpolation_data[1], dtype=float).reshape(-1)
                if not np.any(a_vec):
                    continue

                pairs = IterationDependent._pairs_from_readable(record["pairs"])
                F_basis = _get_lifted_F_basis(k, i, pairs)
                F_vector = (F_basis @ a_vec).reshape(-1)
                eq_constraint_sums[k] = eq_constraint_sums[k] + value * F_vector

            for k in range(0, K):
                residual = np.asarray(eq_constraint_sums[k], dtype=float).reshape(-1)
                max_abs = float(np.max(np.abs(residual))) if residual.size > 0 else 0.0
                l2_norm = float(np.linalg.norm(residual))
                argmax_index = int(np.argmax(np.abs(residual))) if residual.size > 0 else -1
                signed_value = float(residual[argmax_index]) if argmax_index >= 0 else 0.0
                violating_entries = int(np.sum(np.abs(residual) > equality_tolerance))
                violating_equality_entries += violating_entries
                total_equality_entries += int(residual.size)

                entry = {
                    "label": f"iteration={k}",
                    "iteration": k,
                    "dimension": int(residual.size),
                    "max_abs_residual": max_abs,
                    "l2_residual": l2_norm,
                    "argmax_index": argmax_index,
                    "signed_residual_at_argmax": signed_value,
                }
                equality_per_constraint.append(entry)

                if max_abs > largest_equality_violation:
                    largest_equality_violation = max_abs
                    worst_equality_entry = entry

        return {
            "nonnegative": {
                "total_count": len(nonnegative_records),
                "negative_count": len(negative_nonnegative),
                "largest_violation": largest_nonnegative_violation,
                "worst_label": None if worst_nonnegative is None else worst_nonnegative[0],
                "worst_value": None if worst_nonnegative is None else worst_nonnegative[1],
                "top_negative": sorted(negative_nonnegative, key=lambda item: item[1])[:5],
            },
            "psd": {
                "total_count": len(psd_per_constraint),
                "negative_count": sum(1 for entry in psd_per_constraint if float(entry["violation"]) > 0.0),
                "largest_violation": largest_psd_violation,
                "worst_label": None if worst_psd_entry is None else worst_psd_entry["label"],
                "worst_min_eigenvalue": None if worst_psd_entry is None else worst_psd_entry["min_eigenvalue"],
                "per_constraint": psd_per_constraint,
            },
            "equality": {
                "total_count": len(equality_per_constraint),
                "total_entries": total_equality_entries,
                "violating_entries": violating_equality_entries,
                "tolerance": equality_tolerance,
                "largest_violation": largest_equality_violation,
                "worst_label": None if worst_equality_entry is None else worst_equality_entry["label"],
                "worst_index": None if worst_equality_entry is None else worst_equality_entry["argmax_index"],
                "worst_signed_residual": (
                    None if worst_equality_entry is None else worst_equality_entry["signed_residual_at_argmax"]
                ),
                "per_constraint": equality_per_constraint,
            },
        }

    @staticmethod
    def _print_iteration_dependent_diagnostics(
            diagnostics: Dict[str, object],
            K: int,
            c_value: float,
            backend: str,
            verbosity: int,
    ) -> None:
        r"""Print user-facing diagnostics for iteration-dependent verification."""
        if verbosity <= 0:
            return

        nonnegative = diagnostics["nonnegative"]
        psd = diagnostics["psd"]
        equality = diagnostics["equality"]

        print(
            f"[AutoLyap][INFO] Iteration-dependent SDP diagnostics "
            f"(backend={backend}, K={K}, c={c_value:.12g})."
        )
        print(
            f"[AutoLyap][INFO] Nonnegativity check: "
            f"{nonnegative['negative_count']}/{nonnegative['total_count']} constrained scalars are negative; "
            f"largest violation={nonnegative['largest_violation']:.3e}."
        )
        if nonnegative["worst_label"] is not None:
            if int(nonnegative["negative_count"]) > 0:
                print(
                    f"[AutoLyap][INFO] Worst violating constrained scalar value: "
                    f"{float(nonnegative['worst_value']):.3e} at {nonnegative['worst_label']}."
                )
            else:
                print(
                    f"[AutoLyap][INFO] Smallest constrained scalar value (nonnegative): "
                    f"{float(nonnegative['worst_value']):.3e} at {nonnegative['worst_label']}."
                )

        print(
            f"[AutoLyap][INFO] PSD check: "
            f"{psd['negative_count']}/{psd['total_count']} constrained matrices have a negative minimum eigenvalue; "
            f"largest violation={psd['largest_violation']:.3e}."
        )
        if psd["worst_label"] is not None:
            if int(psd["negative_count"]) > 0:
                print(
                    f"[AutoLyap][INFO] Worst PSD minimum eigenvalue: "
                    f"{float(psd['worst_min_eigenvalue']):.3e} at {psd['worst_label']}."
                )
            else:
                print(
                    f"[AutoLyap][INFO] Smallest PSD minimum eigenvalue (nonnegative): "
                    f"{float(psd['worst_min_eigenvalue']):.3e} at {psd['worst_label']}."
                )

        if equality["total_count"] == 0:
            print("[AutoLyap][INFO] Equality check: no active equality constraints.")
        else:
            print(
                f"[AutoLyap][INFO] Equality check: "
                f"{equality['violating_entries']}/{equality['total_entries']} entries exceed "
                f"tol={float(equality['tolerance']):.1e}; "
                f"largest absolute residual={float(equality['largest_violation']):.3e}."
            )
            if equality["worst_label"] is not None:
                print(
                    f"[AutoLyap][INFO] Worst equality residual: "
                    f"{float(equality['worst_signed_residual']):.3e} at "
                    f"{equality['worst_label']}[index={int(equality['worst_index'])}]."
                )

        if verbosity >= 2:
            for entry in psd["per_constraint"]:
                print(
                    f"[AutoLyap][DETAIL] {entry['label']}: "
                    f"min_eigenvalue={float(entry['min_eigenvalue']):.3e}, "
                    f"violation={float(entry['violation']):.3e}."
                )
            for entry in equality["per_constraint"]:
                print(
                    f"[AutoLyap][DETAIL] {entry['label']}: "
                    f"max_abs_residual={float(entry['max_abs_residual']):.3e}, "
                    f"l2_residual={float(entry['l2_residual']):.3e}."
                )
            for label, value in nonnegative["top_negative"]:
                print(
                    f"[AutoLyap][DETAIL] Negative constrained scalar: "
                    f"value={value:.3e} at {label}."
                )

    @staticmethod
    def _validate_iteration_dependent_inputs(
            prob: Type[InclusionProblem],
            algo: Type[Algorithm],
            K: int,
            Q_0: np.ndarray,
            Q_K: np.ndarray,
            q_0: Optional[np.ndarray],
            q_K: Optional[np.ndarray],
        ) -> Tuple[int, int, int, int, int, int, int, int, int, Optional[int]]:
        # -------------------------------------------------------------------------
        # Validate consistency between the problem and the algorithm.
        # -------------------------------------------------------------------------
        if prob.m != algo.m:
            raise ValueError("Mismatch in number of components: prob.m and algo.m must be the same")
        
        # Check that the functional and operator component indices are identical.
        if set(prob.I_func) != set(algo.I_func):
            raise ValueError("Mismatch in functional component indices between prob and algo")
        if set(prob.I_op) != set(algo.I_op):
            raise ValueError("Mismatch in operator component indices between prob and algo")
        
        # Ensure K is positive.
        K = ensure_integral(K, "K", minimum=1)
        
        # -------------------------------------------------------------------------
        # Retrieve dimensions from the algorithm instance.
        # -------------------------------------------------------------------------
        n = algo.n                      # State dimension.
        m_bar = algo.m_bar              # Total evaluations per iteration.
        m = algo.m                      # Total number of components.
        m_bar_func = algo.m_bar_func    # Total evaluations for functional components.
        m_func = algo.m_func            # Number of functional components.
        m_op = algo.m_op                # Number of operator components.
        m_bar_op = algo.m_bar_op        # Total evaluations for operator components.
        
        # Expected dimension for matrices Q: [n + m_bar + m] x [n + m_bar + m].
        dim_Q = n + m_bar + m
        if not (isinstance(Q_0, np.ndarray) and Q_0.ndim == 2 and Q_0.shape[0] == Q_0.shape[1] == dim_Q):
            raise ValueError(
                f"Q_0 must be a symmetric matrix of dimension {dim_Q}x{dim_Q}. "
                f"Got shape {getattr(Q_0, 'shape', None)}."
            )
        ensure_finite_array(Q_0, "Q_0")
        if not np.allclose(Q_0, Q_0.T, atol=1e-8):
            raise ValueError("Q_0 must be symmetric.")
        if not (isinstance(Q_K, np.ndarray) and Q_K.ndim == 2 and Q_K.shape[0] == Q_K.shape[1] == dim_Q):
            raise ValueError(
                f"Q_K must be a symmetric matrix of dimension {dim_Q}x{dim_Q}. "
                f"Got shape {getattr(Q_K, 'shape', None)}."
            )
        ensure_finite_array(Q_K, "Q_K")
        if not np.allclose(Q_K, Q_K.T, atol=1e-8):
            raise ValueError("Q_K must be symmetric.")
        
        # For functional components, q_0 and q_K must have proper dimensions.
        dim_q = None
        if m_func > 0:
            dim_q = m_bar_func + m_func

            # Check q_0
            if q_0 is None:
                raise ValueError(f"q_0 must be a 1D numpy array of length {dim_q}, but got None.")
            if not (isinstance(q_0, np.ndarray) and q_0.ndim == 1 and q_0.shape[0] == dim_q):
                raise ValueError(
                    f"q_0 must be a 1D numpy array of length {dim_q}. Got shape {getattr(q_0, 'shape', None)}."
                )
            ensure_finite_array(q_0, "q_0")

            # Check q_K
            if q_K is None:
                raise ValueError(f"q_K must be a 1D numpy array of length {dim_q}, but got None.")
            if not (isinstance(q_K, np.ndarray) and q_K.ndim == 1 and q_K.shape[0] == dim_q):
                raise ValueError(
                    f"q_K must be a 1D numpy array of length {dim_q}. Got shape {getattr(q_K, 'shape', None)}."
                )
            ensure_finite_array(q_K, "q_K")
        else:
            if q_0 is not None or q_K is not None:
                raise ValueError("q_0 and q_K must be None when there are no functional components.")

        return K, n, m_bar, m, m_bar_func, m_func, m_op, m_bar_op, dim_Q, dim_q

    @staticmethod
    def _expected_pairs_len(interp_key: str) -> int:
        r"""Return the expected interpolation-pair arity for a pattern key."""
        if interp_key == 'r1':
            return 1
        if interp_key in ('r1<r2', 'r1!=r2', 'r1!=star'):
            return 2
        raise ValueError(f"Error: Invalid interpolation indices: {interp_key}.")

    @staticmethod
    def _iter_pair_patterns(
            interp_key: str,
            pairs_with_star: List[Pair],
            pairs_no_star: List[Tuple[int, int]],
            star_pair: Pair,
    ) -> Iterator[PairTuple]:
        r"""Yield concrete pair tuples matching one interpolation-index pattern."""
        if interp_key == 'r1':
            for pair in pairs_with_star:
                yield (pair,)
            return

        if interp_key == 'r1<r2':
            yield from combinations(pairs_with_star, 2)
            return

        if interp_key == 'r1!=r2':
            n_pairs = len(pairs_with_star)
            for idx1 in range(n_pairs):
                pair1 = pairs_with_star[idx1]
                for idx2 in range(n_pairs):
                    if idx1 == idx2:
                        continue
                    yield (pair1, pairs_with_star[idx2])
            return

        if interp_key == 'r1!=star':
            for pair in pairs_no_star:
                yield (pair, star_pair)
            return

        raise ValueError(f"Error: Invalid interpolation indices: {interp_key}.")

    @staticmethod
    def _collect_iteration_dependent_component_data(
            prob: Type[InclusionProblem],
            m: int,
            op_components: set,
    ) -> Dict[int, List[Tuple[InterpolationData, str, bool, bool]]]:
        r"""Validate interpolation payloads and cache per-component metadata."""
        component_data: Dict[int, List[Tuple[InterpolationData, str, bool, bool]]] = {}
        for i in range(1, m + 1):
            is_op = i in op_components
            data = prob.get_component_data(i)
            validated: List[Tuple[InterpolationData, str, bool, bool]] = []
            for o, interp_data in enumerate(data):
                interp_idx = interp_data[1] if is_op else interp_data[3]
                interp_key = str(interp_idx)
                expected_len = IterationDependent._expected_pairs_len(interp_key)
                expected_dim = 2 * expected_len

                if is_op:
                    M, _ = interp_data
                    if getattr(M, 'shape', None) != (expected_dim, expected_dim):
                        raise ValueError(
                            f"Interpolation matrix for component {i}, condition {o} must have "
                            f"shape ({expected_dim}, {expected_dim}) for indices {interp_key}. "
                            f"Got {getattr(M, 'shape', None)}."
                        )
                    has_quadratic = bool(np.any(M))
                    validated.append((interp_data, interp_key, has_quadratic, False))
                else:
                    M, a, _eq, _ = interp_data
                    if getattr(a, 'shape', None) != (expected_len,):
                        raise ValueError(
                            f"Interpolation vector for component {i}, condition {o} must have "
                            f"length {expected_len} for indices {interp_key}. Got {getattr(a, 'shape', None)}."
                        )
                    if getattr(M, 'shape', None) != (expected_dim, expected_dim):
                        raise ValueError(
                            f"Interpolation matrix for component {i}, condition {o} must have "
                            f"shape ({expected_dim}, {expected_dim}) for indices {interp_key}. "
                            f"Got {getattr(M, 'shape', None)}."
                        )
                    has_quadratic = bool(np.any(M))
                    has_linear = bool(np.any(a))
                    validated.append((interp_data, interp_key, has_quadratic, has_linear))
            component_data[i] = validated
        return component_data

    @staticmethod
    def _build_iteration_dependent_model(
            prob: Type[InclusionProblem],
            algo: Type[Algorithm],
            K: int,
            Q_0,
            Q_K,
            q_0,
            q_K,
            dim_Q: int,
            dim_q: Optional[int],
            m_func: int,
            m_op: int,
            model: Optional[Model] = None,
        ) -> Tuple[Model, Dict[str, object]]:
        Mod = model if model is not None else Model()
        c = Mod.variable(1, Domain.greaterThan(0.0))
        
        Qs = {}
        Qs[0] = Q_0
        Qs[K] = Q_K
        Qij_vars: Dict[int, object] = {}
        for k in range(1, K):
            Qij = Mod.variable(f"Q_{k}", dim_Q * (dim_Q + 1) // 2, Domain.unbounded())
            Q_k = create_symmetric_matrix_expression(Qij, dim_Q)
            Qs[k] = Q_k
            Qij_vars[k] = Qij
        
        q_vars: Dict[int, object] = {}
        if m_func > 0:
            qs = {}
            qs[0] = q_0
            qs[K] = q_K
            for k in range(1, K):
                q_k = Mod.variable(f"q_{k}", dim_q, Domain.unbounded())
                qs[k] = q_k
                q_vars[k] = q_k
        
        # ---------------------------------------------------------------------
        # Build the main PSD (positive semidefinite) and equality constraint sums.
        # These will later be constrained to be in the PSD cone or equal zero, respectively.
        # ---------------------------------------------------------------------
        Ws = {}
        (Theta0, Theta1) = IterationDependent._compute_Thetas(algo, 0)
        # First inequality uses the scaled Lyapunov decrease with multiplier c.
        W_0 = Theta1.T @ Qs[1] @ Theta1 - c[0] * Theta0.T @ Qs[0] @ Theta0
        Ws[0] = W_0
        for k in range(1, K):
            (Theta0, Theta1) = IterationDependent._compute_Thetas(algo, k)
            W_k = Theta1.T @ Qs[k+1] @ Theta1 - Theta0.T @ Qs[k] @ Theta0
            Ws[k] = W_k

        if m_func > 0:
            ws = {}
            (theta0, theta1) = IterationDependent._compute_thetas(algo)
            # Linear term for functional components mirrors the quadratic Lyapunov recursion.
            w_0 = theta1.T @ qs[1] - c[0] * theta0.T @ qs[0]
            ws[0] = w_0
            for k in range(1, K):
                w_k = theta1.T @ qs[k+1] - theta0.T @ qs[k]
                ws[k] = w_k

        # Initialize dictionaries to sum up the PSD and equality constraints.
        PSD_constraint_sums = {}
        eq_constraint_sums = {}
        for k in range(0, K):
            PSD_constraint_sums[k] = -Ws[k]
            if m_func > 0:
                eq_constraint_sums[k] = -ws[k]

        # Dictionaries to hold multipliers for interpolation conditions.
        lambdas_op: Dict[Tuple[int, int, PairTuple, int], object] = {}
        lambdas_func: Dict[Tuple[int, int, PairTuple, int], object] = {}
        nus_func: Dict[Tuple[int, int, PairTuple, int], object] = {}

        # ---------------------------------------------------------------------
        # Define inner helper functions for processing interpolation data.
        # These functions handle both operator and function interpolation.
        # ---------------------------------------------------------------------
        n = algo.n
        m_bar = algo.m_bar
        m_bar_func = algo.m_bar_func
        op_components = set(algo.I_op)
        m = algo.m
        m_bar_is = algo.m_bar_is
        compute_E = algo.compute_E
        get_Fs = algo.get_Fs
        mod_variable = Mod.variable
        domain_ge0 = Domain.greaterThan(0.0)
        domain_unbounded = Domain.unbounded()
        star_pair = ('star', 'star')
        lifted_E_cache: Dict[Tuple[int, int, Tuple[Union[Tuple[int, int], Tuple[str, str]], ...]], np.ndarray] = {}
        lifted_F_basis_cache: Dict[Tuple[int, int, Tuple[Union[Tuple[int, int], Tuple[str, str]], ...]], np.ndarray] = {}

        def _get_lifted_E(k, i, pairs):
            cache_key = (k, i, pairs)
            E_matrix = lifted_E_cache.get(cache_key)
            if E_matrix is None:
                E_matrix = compute_E(i, list(pairs), k, k + 1, validate=False)
                lifted_E_cache[cache_key] = E_matrix
            return E_matrix

        def _get_lifted_F_basis(k, i, pairs):
            cache_key = (k, i, pairs)
            F_basis = lifted_F_basis_cache.get(cache_key)
            if F_basis is None:
                Fs_dict = get_Fs(k, k + 1)
                total_dim = 2 * m_bar_func + m_func
                F_basis = np.empty((total_dim, len(pairs)))
                for col_idx, (j, k_idx) in enumerate(pairs):
                    key = (i, 'star', 'star') if (j == 'star' and k_idx == 'star') else (i, j, k_idx)
                    F_basis[:, col_idx] = Fs_dict[key].reshape(-1)
                lifted_F_basis_cache[cache_key] = F_basis
            return F_basis

        def process_pairs(k: int,
                          i: int,
                          o: int,
                          interpolation_data: InterpolationData,
                          pairs: PairTuple,
                          comp_type: str,
                          has_quadratic: bool,
                          has_linear: bool) -> None:
            r"""
            Internal helper for one interpolation-pair pattern.

            Creates multiplier variables and accumulates contributions to the
            PSD/equality constraints at iteration :math:`k`.
            """
            key = (k, i, pairs, o)

            if comp_type == 'op':
                if not has_quadratic:
                    return
                M, _ = interpolation_data
            else:
                M, a, eq, _ = interpolation_data
                if not has_quadratic and not has_linear:
                    return

            # Compute the lifted matrix W for the given pairs.
            W_matrix = None
            if has_quadratic:
                E_matrix = _get_lifted_E(k, i, pairs)
                W_matrix = E_matrix.T @ M @ E_matrix

            if comp_type == 'op':
                lambda_var = mod_variable(1, domain_ge0)
                lambdas_op[key] = lambda_var
                PSD_constraint_sums[k] = PSD_constraint_sums[k] + lambda_var[0] * W_matrix
            else:
                # For functional components, compute the aggregated F vector.
                F_vector = None
                if has_linear:
                    F_basis = _get_lifted_F_basis(k, i, pairs)
                    F_vector = (F_basis @ a).reshape(-1, 1)
                if eq:
                    nu_var = mod_variable(1, domain_unbounded)
                    nus_func[key] = nu_var
                    if has_quadratic:
                        PSD_constraint_sums[k] = PSD_constraint_sums[k] + nu_var[0] * W_matrix
                    if has_linear:
                        eq_constraint_sums[k] = eq_constraint_sums[k] + nu_var[0] * F_vector
                else:
                    lambda_var = mod_variable(1, domain_ge0)
                    lambdas_func[key] = lambda_var
                    if has_quadratic:
                        PSD_constraint_sums[k] = PSD_constraint_sums[k] + lambda_var[0] * W_matrix
                    if has_linear:
                        eq_constraint_sums[k] = eq_constraint_sums[k] + lambda_var[0] * F_vector
        component_data = IterationDependent._collect_iteration_dependent_component_data(
            prob, m, op_components
        )

        # Loop over iterations and process interpolation constraints via explicit pair-pattern iterators.
        for k in range(0, K):
            k_range = range(k, k + 2)
            for i in range(1, m + 1):
                m_bar_i = m_bar_is[i - 1]
                pairs_no_star = [(j, k_) for j in range(1, m_bar_i + 1) for k_ in k_range]
                pairs_with_star = pairs_no_star + [star_pair]
                is_op = i in op_components
                comp_type = 'op' if is_op else 'func'
                for o, (interp_data, interp_key, has_quadratic, has_linear) in enumerate(component_data[i]):
                    for pair_pattern in IterationDependent._iter_pair_patterns(
                        interp_key, pairs_with_star, pairs_no_star, star_pair
                    ):
                        process_pairs(
                            k,
                            i,
                            o,
                            interp_data,
                            pair_pattern,
                            comp_type,
                            has_quadratic,
                            has_linear,
                        )

        # ---------------------------------------------------------------------
        # Add final constraints to the model.
        # ---------------------------------------------------------------------
        for k in range(0, K):
            # Enforce that the PSD constraint sums belong to the PSD cone.
            Mod.constraint(PSD_constraint_sums[k], Domain.inPSDCone(n + 2 * m_bar + m))
            # For functional components, enforce the equality constraint.
            if m_func > 0:
                Mod.constraint(eq_constraint_sums[k] == 0)

        # ---------------------------------------------------------------------
        # Add the objective function to the model.
        # ---------------------------------------------------------------------
        Mod.objective("obj", ObjectiveSense.Minimize, c)

        solution_handles: Dict[str, object] = {
            "K": K,
            "dim_Q": dim_Q,
            "dim_q": dim_q,
            "m_func": m_func,
            "Q_0": Q_0,
            "Q_K": Q_K,
            "q_0": q_0,
            "q_K": q_K,
            "Qij_vars": Qij_vars,
            "q_vars": q_vars,
            "lambdas_op": lambdas_op,
            "lambdas_func": lambdas_func,
            "nus_func": nus_func,
            "c_var": c,
        }
        return Mod, solution_handles

    @staticmethod
    def _build_iteration_dependent_problem_cvxpy(
            prob: Type[InclusionProblem],
            algo: Type[Algorithm],
            K: int,
            Q_0,
            Q_K,
            q_0,
            q_K,
            dim_Q: int,
            dim_q: Optional[int],
            m_func: int,
            m_op: int,
            cp,
    ) -> Tuple[object, Dict[str, object]]:
        r"""Assemble and return the CVXPY problem and variable handles."""
        c = cp.Variable(nonneg=True)

        Qs: Dict[int, Any] = {0: Q_0, K: Q_K}
        Q_vars: Dict[int, object] = {}
        for k in range(1, K):
            Q_k = cp.Variable((dim_Q, dim_Q), symmetric=True)
            Qs[k] = Q_k
            Q_vars[k] = Q_k

        q_vars: Dict[int, object] = {}
        if m_func > 0:
            qs: Dict[int, Any] = {0: q_0, K: q_K}
            for k in range(1, K):
                q_k = cp.Variable(dim_q)
                qs[k] = q_k
                q_vars[k] = q_k

        Ws: Dict[int, Any] = {}
        Theta0, Theta1 = IterationDependent._compute_Thetas(algo, 0)
        Ws[0] = Theta1.T @ Qs[1] @ Theta1 - c * (Theta0.T @ Qs[0] @ Theta0)
        for k in range(1, K):
            Theta0, Theta1 = IterationDependent._compute_Thetas(algo, k)
            Ws[k] = Theta1.T @ Qs[k + 1] @ Theta1 - Theta0.T @ Qs[k] @ Theta0

        if m_func > 0:
            ws: Dict[int, Any] = {}
            theta0, theta1 = IterationDependent._compute_thetas(algo)
            ws[0] = theta1.T @ qs[1] - c * (theta0.T @ qs[0])
            for k in range(1, K):
                ws[k] = theta1.T @ qs[k + 1] - theta0.T @ qs[k]

        PSD_constraint_sums: Dict[int, Any] = {}
        eq_constraint_sums: Dict[int, Any] = {}
        for k in range(0, K):
            PSD_constraint_sums[k] = -Ws[k]
            if m_func > 0:
                eq_constraint_sums[k] = -ws[k]

        lambdas_op: Dict[Tuple[int, int, PairTuple, int], object] = {}
        lambdas_func: Dict[Tuple[int, int, PairTuple, int], object] = {}
        nus_func: Dict[Tuple[int, int, PairTuple, int], object] = {}

        n = algo.n
        m_bar = algo.m_bar
        m_bar_func = algo.m_bar_func
        op_components = set(algo.I_op)
        m = algo.m
        m_bar_is = algo.m_bar_is
        compute_E = algo.compute_E
        get_Fs = algo.get_Fs
        star_pair = ('star', 'star')
        lifted_E_cache: Dict[Tuple[int, int, Tuple[Union[Tuple[int, int], Tuple[str, str]], ...]], np.ndarray] = {}
        lifted_F_basis_cache: Dict[Tuple[int, int, Tuple[Union[Tuple[int, int], Tuple[str, str]], ...]], np.ndarray] = {}

        def _get_lifted_E(k, i, pairs):
            cache_key = (k, i, pairs)
            E_matrix = lifted_E_cache.get(cache_key)
            if E_matrix is None:
                E_matrix = compute_E(i, list(pairs), k, k + 1, validate=False)
                lifted_E_cache[cache_key] = E_matrix
            return E_matrix

        def _get_lifted_F_basis(k, i, pairs):
            cache_key = (k, i, pairs)
            F_basis = lifted_F_basis_cache.get(cache_key)
            if F_basis is None:
                Fs_dict = get_Fs(k, k + 1)
                total_dim = 2 * m_bar_func + m_func
                F_basis = np.empty((total_dim, len(pairs)))
                for col_idx, (j, k_idx) in enumerate(pairs):
                    key = (i, 'star', 'star') if (j == 'star' and k_idx == 'star') else (i, j, k_idx)
                    F_basis[:, col_idx] = Fs_dict[key].reshape(-1)
                lifted_F_basis_cache[cache_key] = F_basis
            return F_basis

        def process_pairs(
                k: int,
                i: int,
                o: int,
                interpolation_data: InterpolationData,
                pairs: PairTuple,
                comp_type: str,
                has_quadratic: bool,
                has_linear: bool) -> None:
            key = (k, i, pairs, o)

            if comp_type == 'op':
                if not has_quadratic:
                    return
                M, _ = interpolation_data
            else:
                M, a, eq, _ = interpolation_data
                if not has_quadratic and not has_linear:
                    return

            W_matrix = None
            if has_quadratic:
                E_matrix = _get_lifted_E(k, i, pairs)
                W_matrix = E_matrix.T @ M @ E_matrix

            if comp_type == 'op':
                lambda_var = cp.Variable(nonneg=True)
                lambdas_op[key] = lambda_var
                PSD_constraint_sums[k] = PSD_constraint_sums[k] + lambda_var * W_matrix
            else:
                F_vector = None
                if has_linear:
                    F_basis = _get_lifted_F_basis(k, i, pairs)
                    F_vector = (F_basis @ a).reshape(-1)
                if eq:
                    nu_var = cp.Variable()
                    nus_func[key] = nu_var
                    if has_quadratic:
                        PSD_constraint_sums[k] = PSD_constraint_sums[k] + nu_var * W_matrix
                    if has_linear:
                        eq_constraint_sums[k] = eq_constraint_sums[k] + nu_var * F_vector
                else:
                    lambda_var = cp.Variable(nonneg=True)
                    lambdas_func[key] = lambda_var
                    if has_quadratic:
                        PSD_constraint_sums[k] = PSD_constraint_sums[k] + lambda_var * W_matrix
                    if has_linear:
                        eq_constraint_sums[k] = eq_constraint_sums[k] + lambda_var * F_vector

        component_data = IterationDependent._collect_iteration_dependent_component_data(
            prob, m, op_components
        )

        for k in range(0, K):
            k_range = range(k, k + 2)
            for i in range(1, m + 1):
                m_bar_i = m_bar_is[i - 1]
                pairs_no_star = [(j, k_) for j in range(1, m_bar_i + 1) for k_ in k_range]
                pairs_with_star = pairs_no_star + [star_pair]
                is_op = i in op_components
                comp_type = 'op' if is_op else 'func'
                for o, (interp_data, interp_key, has_quadratic, has_linear) in enumerate(component_data[i]):
                    for pair_pattern in IterationDependent._iter_pair_patterns(
                        interp_key, pairs_with_star, pairs_no_star, star_pair
                    ):
                        process_pairs(
                            k,
                            i,
                            o,
                            interp_data,
                            pair_pattern,
                            comp_type,
                            has_quadratic,
                            has_linear,
                        )

        constraints = []
        for k in range(0, K):
            constraints.append(PSD_constraint_sums[k] >> 0)
            if m_func > 0:
                constraints.append(eq_constraint_sums[k] == 0)

        problem = cp.Problem(cp.Minimize(c), constraints)
        solution_handles: Dict[str, object] = {
            "K": K,
            "dim_Q": dim_Q,
            "dim_q": dim_q,
            "m_func": m_func,
            "Q_0": Q_0,
            "Q_K": Q_K,
            "q_0": q_0,
            "q_K": q_K,
            "Q_vars": Q_vars,
            "q_vars": q_vars,
            "lambdas_op": lambdas_op,
            "lambdas_func": lambdas_func,
            "nus_func": nus_func,
            "c_var": c,
        }
        return problem, solution_handles

    @staticmethod
    def _pairs_to_readable(pairs: PairTuple) -> List[Dict[str, Union[int, str]]]:
        r"""Convert interpolation-pair tuples into readable dictionaries."""
        return [{"j": pair[0], "k": pair[1]} for pair in pairs]

    @staticmethod
    def _serialize_iteration_dependent_multipliers(
            multiplier_vars: Dict[Tuple[int, int, PairTuple, int], object]
    ) -> List[Dict[str, object]]:
        r"""Convert scalar multiplier variables into readable records."""
        records: List[Dict[str, object]] = []
        for key, var in sorted(
                multiplier_vars.items(),
                key=lambda item: (item[0][0], item[0][1], item[0][3], str(item[0][2]))):
            iteration, component, pairs, interpolation_index = key
            value = IterationDependent._extract_scalar_variable_value(var)
            records.append({
                "iteration": iteration,
                "component": component,
                "interpolation_index": interpolation_index,
                "pairs": IterationDependent._pairs_to_readable(pairs),
                "value": value,
            })
        return records

    @staticmethod
    def _extract_iteration_dependent_certificate(solution_handles: Dict[str, object]) -> Dict[str, object]:
        r"""Extract a solved iteration-dependent certificate into NumPy/Python values."""
        K = int(solution_handles["K"])
        dim_Q = int(solution_handles["dim_Q"])
        m_func = int(solution_handles["m_func"])
        Q_0 = solution_handles["Q_0"]
        Q_K = solution_handles["Q_K"]
        q_0 = solution_handles["q_0"]
        q_K = solution_handles["q_K"]
        Qij_vars = solution_handles["Qij_vars"]
        q_vars = solution_handles["q_vars"]

        Q_sequence: List[np.ndarray] = []
        for k in range(0, K + 1):
            if k == 0:
                Q_k = np.array(Q_0, dtype=float, copy=True)
            elif k == K:
                Q_k = np.array(Q_K, dtype=float, copy=True)
            else:
                Qij_levels = np.asarray(Qij_vars[k].level(), dtype=float).reshape(-1)
                Q_k = create_symmetric_matrix(Qij_levels, dim_Q)
            Q_sequence.append(Q_k)

        q_sequence: Optional[List[np.ndarray]] = None
        if m_func > 0:
            q_sequence = []
            for k in range(0, K + 1):
                if k == 0:
                    q_k = np.array(q_0, dtype=float, copy=True).reshape(-1)
                elif k == K:
                    q_k = np.array(q_K, dtype=float, copy=True).reshape(-1)
                else:
                    q_k = np.asarray(q_vars[k].level(), dtype=float).reshape(-1)
                q_sequence.append(q_k)

        lambdas_op = solution_handles["lambdas_op"]
        lambdas_func = solution_handles["lambdas_func"]
        nus_func = solution_handles["nus_func"]
        return {
            "Q_sequence": Q_sequence,
            "q_sequence": q_sequence,
            "multipliers": {
                "operator_lambda": IterationDependent._serialize_iteration_dependent_multipliers(lambdas_op),
                "function_lambda": IterationDependent._serialize_iteration_dependent_multipliers(lambdas_func),
                "function_nu": IterationDependent._serialize_iteration_dependent_multipliers(nus_func),
            },
        }

    @staticmethod
    def _extract_iteration_dependent_certificate_cvxpy(solution_handles: Dict[str, object]) -> Dict[str, object]:
        r"""Extract a solved CVXPY-backed iteration-dependent certificate."""
        K = int(solution_handles["K"])
        m_func = int(solution_handles["m_func"])
        Q_0 = solution_handles["Q_0"]
        Q_K = solution_handles["Q_K"]
        q_0 = solution_handles["q_0"]
        q_K = solution_handles["q_K"]
        Q_vars = solution_handles["Q_vars"]
        q_vars = solution_handles["q_vars"]

        Q_sequence: List[np.ndarray] = []
        for k in range(0, K + 1):
            if k == 0:
                Q_k = np.array(Q_0, dtype=float, copy=True)
            elif k == K:
                Q_k = np.array(Q_K, dtype=float, copy=True)
            else:
                Q_k = np.asarray(Q_vars[k].value, dtype=float)
            Q_sequence.append(Q_k)

        q_sequence: Optional[List[np.ndarray]] = None
        if m_func > 0:
            q_sequence = []
            for k in range(0, K + 1):
                if k == 0:
                    q_k = np.array(q_0, dtype=float, copy=True).reshape(-1)
                elif k == K:
                    q_k = np.array(q_K, dtype=float, copy=True).reshape(-1)
                else:
                    q_k = np.asarray(q_vars[k].value, dtype=float).reshape(-1)
                q_sequence.append(q_k)

        lambdas_op = solution_handles["lambdas_op"]
        lambdas_func = solution_handles["lambdas_func"]
        nus_func = solution_handles["nus_func"]
        return {
            "Q_sequence": Q_sequence,
            "q_sequence": q_sequence,
            "multipliers": {
                "operator_lambda": IterationDependent._serialize_iteration_dependent_multipliers(lambdas_op),
                "function_lambda": IterationDependent._serialize_iteration_dependent_multipliers(lambdas_func),
                "function_nu": IterationDependent._serialize_iteration_dependent_multipliers(nus_func),
            },
        }

    @staticmethod
    def verify_iteration_dependent_Lyapunov(
            prob: Type[InclusionProblem],
            algo: Type[Algorithm],
            K: int,
            Q_0: np.ndarray,
            Q_K: np.ndarray,
            q_0: Optional[np.ndarray] = None,
            q_K: Optional[np.ndarray] = None,
            solver_options: Optional[SolverOptions] = None,
            verbosity: int = 0,
    ) -> Dict[str, object]:
        r"""
        Verify feasibility of iteration-dependent Lyapunov inequalities via an SDP.

        This method formulates and solves a semidefinite program (SDP)
        for a given inclusion problem, algorithm, and endpoint targets
        :math:`(Q_0,q_0)` and :math:`(Q_K,q_K)`.

        Mathematical notation, star-variable definitions, and Lyapunov ansatzes
        follow the class-level reference in
        :class:`~autolyap.iteration_dependent.IterationDependent`.

        **Enforced inequalities**

        The method enforces the chained Lyapunov inequalities

        .. math::
            \mathcal{V}(K) \le \mathcal{V}(K-1) \le \cdots \le \mathcal{V}(1) \le c\,\mathcal{V}(0).

        with :math:`c \ge 0`.

        **User-specified targets**

        The user sets the endpoint parameters :math:`(Q_0,q_0)` and :math:`(Q_K,q_K)`.
        These endpoint parameters are fixed inputs to the SDP (not optimization variables).
        The SDP then searches for intermediate :math:`(Q_k,q_k)` for
        :math:`k \in \llbracket 1, K-1\rrbracket` and the minimum feasible :math:`c`.
        When :math:`\NumFunc = 0`, the vectors :math:`q_k` (and inputs `q_0`, `q_K`) are omitted.

        The Lyapunov values are

        .. math::
            \mathcal{V}(k)
            =
            \inner{
            \boldsymbol{z}_{\mathcal{V}}^{k}
            }{
            (Q_k \kron \Id)\boldsymbol{z}_{\mathcal{V}}^{k}
            }
            + q_{k}^{\top}\boldsymbol{f}_{\mathcal{V}}^{k},

        where

        .. math::
            \boldsymbol{z}_{\mathcal{V}}^{k}
            =
            \begin{bmatrix}
            \bx^{k} \\ \bu^{k} \\ \hat{\bu}^{\star} \\ y^{\star}
            \end{bmatrix}, \qquad
            \boldsymbol{f}_{\mathcal{V}}^{k}
            =
            \begin{bmatrix}
            \bFcn^{k} \\ \bFcn^{\star}
            \end{bmatrix}.

        **Parameters**

        - `prob` (:class:`~typing.Type`\[:class:`~autolyap.problemclass.InclusionProblem`\]): An
          :class:`~autolyap.problemclass.InclusionProblem`
          instance containing interpolation conditions.
        - `algo` (:class:`~typing.Type`\[:class:`~autolyap.algorithms.Algorithm`\]): An
          :class:`~autolyap.algorithms.Algorithm` instance providing
          dimensions and matrix helpers.
        - `K` (:class:`int`): A positive integer corresponding to :math:`K` defining the iteration budget.
        - `Q_0` (:class:`numpy.ndarray`): A symmetric matrix corresponding to
          :math:`Q_0 \in \sym^{n + \NumEval + m}`.
        - `Q_K` (:class:`numpy.ndarray`): A symmetric matrix corresponding to
          :math:`Q_K \in \sym^{n + \NumEval + m}`.
        - `q_0` (:class:`~typing.Optional`\[:class:`numpy.ndarray`\]): A vector corresponding to
          :math:`q_0 \in \mathbb{R}^{\NumEvalFunc + \NumFunc}` for functional components
          (required if :math:`\NumFunc > 0`; otherwise `None`).
        - `q_K` (:class:`~typing.Optional`\[:class:`numpy.ndarray`\]): A vector corresponding to
          :math:`q_K \in \mathbb{R}^{\NumEvalFunc + \NumFunc}` for functional components
          (required if :math:`\NumFunc > 0`; otherwise `None`).
        - `solver_options` (:class:`~typing.Optional`\[:class:`~autolyap.solver_options.SolverOptions`\]):
          Optional backend and parameter settings. Defaults to
          `SolverOptions(backend="mosek_fusion")`.
        - `verbosity` (:class:`int`): Nonnegative output level. `0` disables user-facing
          diagnostics, `1` prints concise summaries, and `2` adds per-iteration detail.

        **Returns**

        - (:class:`~typing.Dict`\[:class:`str`, :class:`object`\]): Result dictionary
          with keys `success`, `c`, and `certificate`.

          - `success` (:class:`bool`): `True` iff the SDP is feasible.
          - `c` (:class:`~typing.Optional`\[:class:`float`\]): Optimal objective value when
            `success` is `True`; otherwise `None`.
          - `certificate` (:class:`~typing.Optional`\[:class:`~typing.Dict`\[:class:`str`, :class:`object`\]\]):
            `None` when `success` is `False`; otherwise a feasible certificate.

          When `success` is `True`, `certificate` has:

          .. code-block:: text

              {
                "Q_sequence": List[np.ndarray],   # length K+1, Q_sequence[k] = Q_k
                "q_sequence": List[np.ndarray] | None,  # None when m_func == 0
                "multipliers": {
                  "operator_lambda": List[record],
                  "function_lambda": List[record],
                  "function_nu": List[record]
                }
              }

          Each multiplier list entry is a `record` with:

          .. code-block:: text

              record = {
                "iteration": int,
                "component": int,
                "interpolation_index": int,
                "pairs": List[{"j": int | "star", "k": int | "star"}],
                "value": float
              }

          Field meanings and ranges:

          - `iteration` corresponds to :math:`k` and satisfies
            :math:`k \in \llbracket 0, K-1 \rrbracket`.
          - `component` corresponds to :math:`i` and satisfies
            :math:`i \in \llbracket 1, m \rrbracket`.
          - `interpolation_index` corresponds to :math:`o`, where
            :math:`o` is the zero-based index from
            :math:`\text{enumerate}(\text{prob.get_component_data}(i))`, so
            :math:`o \in \llbracket 0, \text{len}(\text{prob.get_component_data}(i)) - 1 \rrbracket`.
          - `pairs` is the concrete interpolation-pair list used by that multiplier.
            Its length is 1 (pattern `"r1"`) or 2 (patterns `"r1<r2"`,
            `"r1!=r2"`, `"r1!=star"`). Typical examples are
            `[{"j": 2, "k": 5}]` and
            `[{"j": 1, "k": 5}, {"j": "star", "k": "star"}]`.

            Pair entries satisfy

            .. math::
                \begin{aligned}
                j &\in \llbracket 1, \bar m_i \rrbracket \cup \{\star\}, \\
                k_{\text{pair}} &\in \{k, k+1\} \cup \{\star\},
                \end{aligned}

            with :math:`j=\star \Leftrightarrow k_{\text{pair}}=\star`.
          - `value` is the scalar multiplier for that record.

        **Raises**

        - `ValueError`: If input dimensions or other conditions are violated.

        **Notes**

        - Default backend is MOSEK Fusion. You may also select CVXPY via
          `SolverOptions(backend="cvxpy")`.
        """
        K, _, _, _, _, m_func, m_op, _, dim_Q, dim_q = IterationDependent._validate_iteration_dependent_inputs(
            prob, algo, K, Q_0, Q_K, q_0, q_K
        )
        verbosity = ensure_integral(verbosity, "verbosity", minimum=0)
        solver_options = normalize_solver_options(solver_options)

        if solver_options.backend == "mosek_fusion":
            Mod = Model()
            Mod, solution_handles = IterationDependent._build_iteration_dependent_model(
                prob,
                algo,
                K,
                Q_0,
                Q_K,
                q_0,
                q_K,
                dim_Q,
                dim_q,
                m_func,
                m_op,
                model=Mod,
            )
            IterationDependent._apply_mosek_solver_params(Mod, solver_options)
            c_var = solution_handles["c_var"]
            if verbosity > 0:
                print(
                    f"[AutoLyap][INFO] Solving iteration-dependent SDP "
                    f"(backend={solver_options.backend}, K={K})."
                )

            try:
                Mod.solve()
                Mod.primalObjValue()
                c_val = IterationDependent._extract_scalar_variable_value(c_var)
                certificate = IterationDependent._extract_iteration_dependent_certificate(solution_handles)
                if verbosity > 0:
                    try:
                        diagnostics = IterationDependent._compute_iteration_dependent_diagnostics(
                            prob,
                            algo,
                            K,
                            c_val,
                            certificate,
                        )
                        IterationDependent._print_iteration_dependent_diagnostics(
                            diagnostics,
                            K,
                            c_val,
                            solver_options.backend,
                            verbosity,
                        )
                    except Exception as exc:
                        print(
                            f"[AutoLyap][WARN] Unable to compute diagnostic summary: {exc}."
                        )
                return {"success": True, "c": c_val, "certificate": certificate}
            except OptimizeError as e:
                licence_markers = (
                    "err_license_max",         # 1016 – all floating tokens in use
                    "err_license_server",      # 1015 – server unreachable / down
                    "err_missing_license_file" # 1008 – no licence file / server path
                )
                if any(mark in str(e) for mark in licence_markers):
                    raise
                if verbosity > 0:
                    print(
                        f"[AutoLyap][INFO] Iteration-dependent SDP is infeasible or not solved for K={K}."
                    )
                return {"success": False, "c": None, "certificate": None}
            except Exception:
                if verbosity > 0:
                    print(
                        f"[AutoLyap][INFO] Iteration-dependent SDP is infeasible or not solved for K={K}."
                    )
                return {"success": False, "c": None, "certificate": None}
            finally:
                Mod.dispose()

        cp = IterationDependent._import_cvxpy()
        problem, solution_handles = IterationDependent._build_iteration_dependent_problem_cvxpy(
            prob,
            algo,
            K,
            Q_0,
            Q_K,
            q_0,
            q_K,
            dim_Q,
            dim_q,
            m_func,
            m_op,
            cp=cp,
        )
        solve_kwargs = get_cvxpy_solve_kwargs(solver_options)
        accepted_statuses = get_cvxpy_accepted_statuses(cp, solver_options)
        if verbosity > 0:
            print(
                f"[AutoLyap][INFO] Solving iteration-dependent SDP "
                f"(backend={solver_options.backend}, K={K})."
            )
        try:
            problem.solve(**solve_kwargs)
        except Exception:
            if verbosity > 0:
                print(
                    f"[AutoLyap][INFO] Iteration-dependent SDP solve failed for K={K}."
                )
            return {"success": False, "c": None, "certificate": None}

        if problem.status not in accepted_statuses:
            if verbosity > 0:
                print(
                    f"[AutoLyap][INFO] Iteration-dependent SDP status={problem.status}; no feasible certificate for K={K}."
                )
            return {"success": False, "c": None, "certificate": None}

        c_val = IterationDependent._extract_scalar_variable_value(solution_handles["c_var"])
        certificate = IterationDependent._extract_iteration_dependent_certificate_cvxpy(solution_handles)
        if verbosity > 0:
            try:
                diagnostics = IterationDependent._compute_iteration_dependent_diagnostics(
                    prob,
                    algo,
                    K,
                    c_val,
                    certificate,
                )
                IterationDependent._print_iteration_dependent_diagnostics(
                    diagnostics,
                    K,
                    c_val,
                    solver_options.backend,
                    verbosity,
                )
            except Exception as exc:
                print(
                    f"[AutoLyap][WARN] Unable to compute diagnostic summary: {exc}."
                )
        return {"success": True, "c": c_val, "certificate": certificate}

    @staticmethod
    def _compute_Thetas(algo: Type[Algorithm], k: int) -> Tuple[np.ndarray, np.ndarray]:
        r"""
        Compute the capital :math:`\Theta` matrices for the iteration-dependent Lyapunov context.

        The matrices are defined as follows:

        .. math::
            
            \Theta_{0} =
            \begin{bmatrix}
            I_{n+\NumEval} & 0_{(n+\NumEval)\times\NumEval} & 0_{(n+\NumEval)\times m} \\
            0_{m\times(n+\NumEval)} & 0_{m\times\NumEval} & I_{m}
            \end{bmatrix}

        and

        .. math::
            
            \Theta_{1}^{(k)} =
            \begin{bmatrix}
            X_{k+1}^{k,k+1} \\
            0_{(\NumEval+m)\times(n+\NumEval)} \quad I_{(\NumEval+m)}
            \end{bmatrix}

        **Definitions**

        - :math:`n` is given by `algo.n`.
        - :math:`\NumEval` is given by `algo.m_bar`.
        - :math:`m` is given by `algo.m`.
        - :math:`X_{k+1}^{k,k+1}` is retrieved via :meth:`~autolyap.algorithms.Algorithm.get_Xs` with
          `k_min = k` and `k_max = k+1`, using key :math:`k+1`.

        **Parameters**

        - `algo` (:class:`~typing.Type`\[:class:`~autolyap.algorithms.Algorithm`\]): An instance of :class:`~autolyap.algorithms.Algorithm`.
        - `k` (:class:`int`): A non-negative integer iteration index corresponding to :math:`k` used to select
          the appropriate :math:`X` matrix.

        **Returns**

        - (:class:`~typing.Tuple`\[:class:`numpy.ndarray`, :class:`numpy.ndarray`\]): A tuple :math:`(\Theta_0, \Theta_1)` of numpy arrays.

        **Raises**

        - `ValueError`: If :math:`k` is negative or the required :math:`X` matrix is missing.
        """

        k = ensure_integral(k, "k", minimum=0)
        
        n = algo.n
        m_bar = algo.m_bar
        m = algo.m

        # Construct Theta_{0}
        Theta0 = np.block([
            [np.eye(n + m_bar), np.zeros((n + m_bar, m_bar)), np.zeros((n + m_bar, m))],
            [np.zeros((m, n + m_bar)), np.zeros((m, m_bar)), np.eye(m)]
        ])

        # Retrieve X_{k+1}^{k,k+1} using algo.get_Xs(k, k+1)
        Xs = algo.get_Xs(k, k+1)
        if (k + 1) not in Xs:
            raise ValueError(f"Expected key {k+1} in X matrices, but it was not found.")
        X_block = Xs[k + 1]

        # Construct the lower block for Theta_{1}^{(k)}
        lower_block = np.hstack([
            np.zeros((m_bar + m, n + m_bar)),
            np.eye(m_bar + m)
        ])

        # Form Theta_{1}^{(k)} by vertically stacking X_block and the lower block
        Theta1 = np.vstack([X_block, lower_block])
        return Theta0, Theta1

    @staticmethod
    def _compute_thetas(algo: Type[Algorithm]) -> Tuple[np.ndarray, np.ndarray]:
        r"""
        Compute the lowercase :math:`\theta` matrices for the iteration-dependent Lyapunov context.

        The matrices are defined as follows:

        .. math::

            \theta_{0} =
            \begin{bmatrix}
            I_{\NumEvalFunc} & 0_{\NumEvalFunc \times \NumEvalFunc} & 0_{\NumEvalFunc \times \NumFunc} \\
            0_{\NumFunc \times \NumEvalFunc} & 0_{\NumFunc \times \NumEvalFunc} & I_{\NumFunc}
            \end{bmatrix}

        and

        .. math::

            \theta_{1} =
            \begin{bmatrix}
            0_{(\NumEvalFunc+\NumFunc) \times \NumEvalFunc} & I_{(\NumEvalFunc+\NumFunc)}
            \end{bmatrix}

        **Definitions**

        - :math:`\NumEvalFunc` is given by `algo.m_bar_func`.
        - :math:`\NumFunc` is given by `algo.m_func`.

        **Notes**

        - The :math:`\theta` matrices are only defined when there is at least one functional component.

        **Parameters**

        - `algo` (:class:`~typing.Type`\[:class:`~autolyap.algorithms.Algorithm`\]): An instance of :class:`~autolyap.algorithms.Algorithm`.

        **Returns**

        - (:class:`~typing.Tuple`\[:class:`numpy.ndarray`, :class:`numpy.ndarray`\]): A tuple :math:`(\theta_{0}, \theta_{1})` of numpy arrays.

        **Raises**

        - `ValueError`: If there are no functional components.
        """
        m_bar_func = algo.m_bar_func  
        m_func = algo.m_func          
        if m_func <= 0:
            raise ValueError("Theta matrices require at least one functional component (m_func > 0).")

        theta0 = np.block([
            [np.eye(m_bar_func), np.zeros((m_bar_func, m_bar_func)), np.zeros((m_bar_func, m_func))],
            [np.zeros((m_func, m_bar_func)), np.zeros((m_func, m_bar_func)), np.eye(m_func)]
        ])

        theta1 = np.hstack([
            np.zeros((m_bar_func + m_func, m_bar_func)),
            np.eye(m_bar_func + m_func)
        ])

        return theta0, theta1

    @staticmethod
    def get_parameters_distance_to_solution(
            algo: Type[Algorithm],
            k: int,
            i: int = 1,
            j: int = 1
        ) -> Union[np.ndarray, Tuple[np.ndarray, np.ndarray]]:
        r"""
        Compute Lyapunov parameters for the distance-to-solution metric at iteration :math:`k`.

        Mathematical notation and shared definitions follow the class-level
        reference in :class:`~autolyap.iteration_dependent.IterationDependent`.

        This method computes

        .. math::
            Q_k
            =
            \left(P_{(i,j)}Y_k^{k,k} - P_{(i,\star)}Y_\star^{k,k}\right)^\top
            \left(P_{(i,j)}Y_k^{k,k} - P_{(i,\star)}Y_\star^{k,k}\right),

        where :math:`Y_k^{k,k}` and :math:`Y_\star^{k,k}` come from
        :meth:`~autolyap.algorithms.Algorithm.get_Ys` with `k_min = k`, `k_max = k`,
        and :math:`P_{(i,j)}` and :math:`P_{(i,\star)}` come from
        :meth:`~autolyap.algorithms.Algorithm.get_Ps`.

        If `algo.m_func > 0`, the method also returns :math:`q_k = 0`.

        **Resulting lower bound**

        With this choice of :math:`(Q_k,q_k)`,

        .. math::
            \mathcal{V}(k) = \|y_{i,j}^{k} - y^{\star}\|^{2}.

        **Parameters**

        - `algo` (:class:`~typing.Type`\[:class:`~autolyap.algorithms.Algorithm`\]): Algorithm instance providing `m`, `m_bar_is`,
          :meth:`~autolyap.algorithms.Algorithm.get_Ys`, and
          :meth:`~autolyap.algorithms.Algorithm.get_Ps`.
        - `k` (:class:`int`): Nonnegative iteration index :math:`k`.
        - `i` (:class:`int`): Component index, with
          :math:`i \in \llbracket 1, m\rrbracket`.
        - `j` (:class:`int`): Evaluation index for component `i`, with
          :math:`j \in \llbracket 1, \NumEval_i\rrbracket`.

        **Returns**

        - (:class:`~typing.Union`\[:class:`numpy.ndarray`, :class:`~typing.Tuple`\[:class:`numpy.ndarray`, :class:`numpy.ndarray`\]\]):
          If `algo.m_func == 0`, returns :math:`Q_k` with

          .. math::
              Q_k \in \sym^{n + \NumEval + m}.

          Otherwise, returns :math:`(Q_k, q_k)` with

          .. math::
              \begin{aligned}
              Q_k &\in \sym^{n + \NumEval + m},\\
              q_k &\in \mathbb{R}^{\NumEvalFunc + \NumFunc}.
              \end{aligned}

        **Raises**

        - `ValueError`: If an input is invalid or a required matrix is missing.
        """
        # ----- Input Checking -----
        k = ensure_integral(k, "k", minimum=0)
        i = ensure_integral(i, "i", minimum=1)
        if i > algo.m:
            raise ValueError(f"Component index i must be in [1, {algo.m}]. Got {i}.")
        j = ensure_integral(j, "j", minimum=1)
        if j > algo.m_bar_is[i - 1]:
            raise ValueError(f"For component {i}, evaluation index j must be in [1, {algo.m_bar_is[i - 1]}]. Got {j}.")

        # ----- Compute Q_k -----
        Ys = algo.get_Ys(k, k)
        if k not in Ys:
            raise ValueError(f"Y matrix for iteration k = {k} not found.")
        if 'star' not in Ys:
            raise ValueError("Y star matrix ('star') not found.")
        
        Ps = algo.get_Ps()
        if (i, j) not in Ps:
            raise ValueError(f"Projection matrix for component {i}, evaluation {j} not found.")
        if (i, 'star') not in Ps:
            raise ValueError(f"Projection matrix for component {i} star not found.")
        
        diff = Ps[(i, j)] @ Ys[k] - Ps[(i, 'star')] @ Ys['star']
        Q_k = diff.T @ diff
        
        # ----- Construct T, p, and t as zeros with appropriate dimensions -----
        if algo.m_func > 0:
            m_bar_func = algo.m_bar_func    # Total evaluations for functional components.
            m_func = algo.m_func            # Number of functional components.
            dim_q_k = m_bar_func + m_func
            q_k_vec = np.zeros(dim_q_k)
            return Q_k, q_k_vec
        else:
            return Q_k
    
    @staticmethod
    def get_parameters_function_value_suboptimality(
            algo: Type[Algorithm], 
            k: int, 
            j: int = 1
        ) -> Tuple[np.ndarray, np.ndarray]:
        r"""
        Compute Lyapunov parameters for function-value suboptimality at iteration :math:`k`.

        Mathematical notation and shared definitions follow the class-level
        reference in :class:`~autolyap.iteration_dependent.IterationDependent`.
        This method is defined only when :math:`m = \NumFunc = 1`.

        The returned parameters satisfy

        .. math::
            Q_k = 0, \qquad
            q_k = \left(F_{(1,j,k)}^{k,k} - F_{(1,\star,\star)}^{k,k}\right)^\top,

        where both :math:`F` matrices are retrieved from
        :meth:`~autolyap.algorithms.Algorithm.get_Fs` with `k_min = k`, `k_max = k`.

        **Resulting lower bound**

        With this choice of :math:`(Q_k,q_k)`,

        .. math::
            \mathcal{V}(k) = f_{1}(y_{1,j}^{k}) - f_{1}(y^{\star}).

        **Parameters**

        - `algo` (:class:`~typing.Type`\[:class:`~autolyap.algorithms.Algorithm`\]): Algorithm instance with `m = m_func = 1`,
          `m_bar_is`, and :meth:`~autolyap.algorithms.Algorithm.get_Fs`.
        - `k` (:class:`int`): Nonnegative iteration index :math:`k`.
        - `j` (:class:`int`): Evaluation index for component 1, with
          :math:`j \in \llbracket 1, \NumEval_1\rrbracket`.

        **Returns**

        - (:class:`~typing.Tuple`\[:class:`numpy.ndarray`, :class:`numpy.ndarray`\]):
          A tuple :math:`(Q_k, q_k)` with

          .. math::
              \begin{aligned}
              Q_k &\in \sym^{n + \NumEval + m},\\
              q_k &\in \mathbb{R}^{\NumEvalFunc + \NumFunc}.
              \end{aligned}

        **Raises**

        - `ValueError`: If an input is invalid, required :math:`F` matrices are missing,
          or :math:`m \ne 1` / :math:`\NumFunc \ne 1`.
        """
        # ----- Input Checking -----
        k = ensure_integral(k, "k", minimum=0)
        j = ensure_integral(j, "j", minimum=1)
        if j > algo.m_bar_is[0]:
            raise ValueError(f"For component 1, evaluation index j must be in [1, {algo.m_bar_is[0]}]. Got {j}.")
        if algo.m != 1 or algo.m_func != 1:
            raise ValueError("Function value suboptimality is defined only for problems with a single functional component (m = m_func = 1).")

        # ----- Dimensions for Q_k -----
        dim_Q_k = algo.n + algo.m_bar + algo.m
        Q_k = np.zeros((dim_Q_k, dim_Q_k))

        # ----- Compute q_k -----
        Fs = algo.get_Fs(k, k)
        key_nonstar = (1, j, k)
        key_star = (1, 'star', 'star')
        if key_nonstar not in Fs:
            raise ValueError(f"F matrix for key {key_nonstar} not found.")
        if key_star not in Fs:
            raise ValueError("F star matrix (1, 'star', 'star') not found.")
        F_nonstar = Fs[key_nonstar]
        F_star = Fs[key_star]
        q_k = (F_nonstar - F_star).T
        q_k = np.ravel(q_k)

        return Q_k, q_k

    @staticmethod
    def get_parameters_fixed_point_residual(
            algo: Type[Algorithm], 
            k: int
        ) -> Union[np.ndarray, Tuple[np.ndarray, np.ndarray]]:
        r"""
        Compute Lyapunov parameters for the fixed-point residual at iteration :math:`k`.

        Mathematical notation and shared definitions follow the class-level
        reference in :class:`~autolyap.iteration_dependent.IterationDependent`.

        This method computes

        .. math::
            Q_k
            =
            \left(X_{k+1}^{k,k} - X_k^{k,k}\right)^\top
            \left(X_{k+1}^{k,k} - X_k^{k,k}\right),

        using :math:`X_k^{k,k}` and :math:`X_{k+1}^{k,k}` from
        :meth:`~autolyap.algorithms.Algorithm.get_Xs` with `k_min = k`, `k_max = k`.

        If `algo.m_func > 0`, the method also returns :math:`q_k = 0`.

        **Resulting lower bound**

        With this choice of :math:`(Q_k,q_k)`,

        .. math::
            \mathcal{V}(k) = \|\bx^{k+1} - \bx^{k}\|^{2}.

        **Parameters**

        - `algo` (:class:`~typing.Type`\[:class:`~autolyap.algorithms.Algorithm`\]): Algorithm instance providing dimensions and
          :meth:`~autolyap.algorithms.Algorithm.get_Xs`.
        - `k` (:class:`int`): Nonnegative iteration index :math:`k`.

        **Returns**

        - (:class:`~typing.Union`\[:class:`numpy.ndarray`, :class:`~typing.Tuple`\[:class:`numpy.ndarray`, :class:`numpy.ndarray`\]\]):
          If `algo.m_func == 0`, returns :math:`Q_k` with

          .. math::
              Q_k \in \sym^{n + \NumEval + m}.

          Otherwise, returns :math:`(Q_k, q_k)` with

          .. math::
              \begin{aligned}
              Q_k &\in \sym^{n + \NumEval + m},\\
              q_k &\in \mathbb{R}^{\NumEvalFunc + \NumFunc}.
              \end{aligned}

        **Raises**

        - `ValueError`: If an input is invalid or required :math:`X` matrices are missing.
        """
        # ----- Input Checking -----
        k = ensure_integral(k, "k", minimum=0)

        # ----- Retrieve X matrices -----
        Xs = algo.get_Xs(k, k)
        if k not in Xs or (k + 1) not in Xs:
            raise ValueError(f"X matrices for iterations {k} and {k+1} not found.")

        # ----- Compute Q_k -----
        diff = Xs[k + 1] - Xs[k]
        Q_k = diff.T @ diff

        # ----- Set q_k to zero -----
        if algo.m_func > 0:
            q_dim = algo.m_bar_func + algo.m_func
            q_k = np.zeros(q_dim)
            return Q_k, q_k
        else:
            return Q_k

    @staticmethod
    def get_parameters_optimality_measure(
            algo: Type[Algorithm], 
            k: int
        ) -> Union[np.ndarray, Tuple[np.ndarray, np.ndarray]]:
        r"""
        Compute Lyapunov parameters for the optimality measure at iteration :math:`k`.

        Mathematical notation and shared definitions follow the class-level
        reference in :class:`~autolyap.iteration_dependent.IterationDependent`.

        This method computes

        .. math::
            Q_k
            =
            \begin{cases}
                \left(P_{(1,1)}U_k^{k,k}\right)^\top \left(P_{(1,1)}U_k^{k,k}\right), & \text{if } m = 1, \\[1em]
                \left(\sum_{i=1}^{m} P_{(i,1)}U_k^{k,k}\right)^\top
                \left(\sum_{i=1}^{m} P_{(i,1)}U_k^{k,k}\right)
                + \sum_{i=2}^{m}
                \left(\left(P_{(1,1)} - P_{(i,1)}\right)Y_k^{k,k}\right)^\top
                \left(\left(P_{(1,1)} - P_{(i,1)}\right)Y_k^{k,k}\right),
                & \text{if } m > 1,
            \end{cases}

        using :math:`U_k^{k,k}`, :math:`Y_k^{k,k}`, and projection matrices from
        :meth:`~autolyap.algorithms.Algorithm.get_Us`,
        :meth:`~autolyap.algorithms.Algorithm.get_Ys`, and
        :meth:`~autolyap.algorithms.Algorithm.get_Ps`.

        If `algo.m_func > 0`, the method also returns :math:`q_k = 0`.

        **Resulting lower bound**

        With this choice of :math:`(Q_k,q_k)`,

        .. math::
            \mathcal{V}(k)
            =
            \begin{cases}
                \|u_{1,1}^{k}\|^{2}, & \text{if } m = 1, \\[0.5em]
                \left\|\sum_{i=1}^{m} u_{i,1}^{k}\right\|^{2}
                + \sum_{i=2}^{m} \|y_{1,1}^{k} - y_{i,1}^{k}\|^{2},
                & \text{if } m > 1.
            \end{cases}

        **Parameters**

        - `algo` (:class:`~typing.Type`\[:class:`~autolyap.algorithms.Algorithm`\]): Algorithm instance providing `m`, `m_bar`, `m_bar_is`,
          :meth:`~autolyap.algorithms.Algorithm.get_Us`,
          :meth:`~autolyap.algorithms.Algorithm.get_Ys`, and
          :meth:`~autolyap.algorithms.Algorithm.get_Ps`.
        - `k` (:class:`int`): Nonnegative iteration index :math:`k`.

        **Returns**

        - (:class:`~typing.Union`\[:class:`numpy.ndarray`, :class:`~typing.Tuple`\[:class:`numpy.ndarray`, :class:`numpy.ndarray`\]\]):
          If `algo.m_func == 0`, returns :math:`Q_k` with

          .. math::
              Q_k \in \sym^{n + \NumEval + m}.

          Otherwise, returns :math:`(Q_k, q_k)` with

          .. math::
              \begin{aligned}
              Q_k &\in \sym^{n + \NumEval + m},\\
              q_k &\in \mathbb{R}^{\NumEvalFunc + \NumFunc}.
              \end{aligned}

        **Raises**

        - `ValueError`: If an input is invalid or required matrices are missing.
        """
        # ----- Input Checking -----
        k = ensure_integral(k, "k", minimum=0)

        # ----- Retrieve U and Y matrices -----
        Us = algo.get_Us(k, k)
        Ys = algo.get_Ys(k, k)
        if k not in Us:
            raise ValueError(f"U matrix for iteration {k} not found.")
        if k not in Ys:
            raise ValueError(f"Y matrix for iteration {k} not found.")
        
        # ----- Retrieve Projection matrices -----
        Ps = algo.get_Ps()

        # ----- Compute Q_k -----
        if algo.m == 1:
            # Q_k = (P_{(1,1)}U_{k}^{k,k})^{\top} P_{(1,1)}U_{k}^{k,k}
            if algo.m_bar_is[0] < 1:
                raise ValueError("Optimality measure requires at least one evaluation for component 1.")
            P = Ps[(1, 1)]
            U = Us[k]
            term = P @ U
            Q_k = term.T @ term
        else:
            if any(m_bar_i < 1 for m_bar_i in algo.m_bar_is):
                raise ValueError("Optimality measure requires each component to have at least one evaluation.")
            # m > 1:
            # term1 = (sum_{i=1}^{m} P_{(i,1)}U_{k}^{k,k})^{\top} (sum_{i=1}^{m} P_{(i,1)}U_{k}^{k,k})
            S = None
            for i in range(1, algo.m + 1):
                P_i = Ps[(i, 1)]
                if S is None:
                    S = P_i @ Us[k]
                else:
                    S = S + P_i @ Us[k]
            term1 = S.T @ S
            
            # term2 = sum_{i=2}^{m} ((P_{(1,1)} - P_{(i,1)})Y_{k}^{k,k})^{\top} ((P_{(1,1)} - P_{(i,1)})Y_{k}^{k,k})
            Y = Ys[k]
            term2 = 0
            for i in range(2, algo.m + 1):
                diff_P = Ps[(1, 1)] - Ps[(i, 1)]
                temp = diff_P @ Y
                term2 = term2 + (temp.T @ temp)
            Q_k = term1 + term2

        # ----- Set q_k to zero -----
        if algo.m_func > 0:
            q_dim = algo.m_bar_func + algo.m_func
            q_k = np.zeros(q_dim)
            return Q_k, q_k
        else:
            return Q_k
